---
name: TNTRun
main: TNTRun\Main
version: 1.0.0
api: [1.12.0]
load: POSTWORLD
author: ItalianDevs4PM
authors: [Flavius12, fycarman, luca28pet, XEmAX32, xionbig]
description: A Mini-Game plugin for PocketMine servers!
website: https://github.com/ItalianDevs4PM/TNTRun